### ISSUE TITLE
Remove make.bat

### ISSUE THREAD

**Issue by shaardie** [emissions-api/emissions-api#101]
Since I do not use Windows, I have no idea if `docs/make.bat` is working or not. Has anybody used this anyway? I would say we should remove it.

This is probably the same question for [sentinel5dl](https://github.com/emissions-api/sentinel5dl) and [sentinel5algorithms](https://github.com/emissions-api/sentinel5algorithms). I would say if we agree on removing the file, we should do the same in those repositories.

**Comment by EmbeddedHenni** [comment]
after `pip install -U sphinx` and `pip install sphinx-rtd-theme` `docs/make.bat` was working perfectly fine. but `sphinx-build -b html sourcedir builddir` did the same so i think it is obsolete

**Comment by benszau** [comment]
The question is, if we want to (or if we even can) support windows as a target platform. If we decide to support windows, we could keep such files. If not, we should drop these files to reduce confusion about if or if not we support windows.

**Comment by shaardie** [comment]
IMHO at the end we will not support Windows, since we want users to use our service not having their own setup. So the targeted OS is what we want to run on our server. And that is very very likely not Windows :smile:

**Comment by benszau** [comment]
I agree on that. For a desktop setup, windows could be interesting but for the server setup, windows is of no importance to us 👍
