### ISSUE TITLE
Make PATH in preprocess.py configurable

### ISSUE THREAD

**Issue by shaardie** [emissions-api/emissions-api#14]
The current path where the data has to be stored is hard coded in the python code. It should be configurable.

This can be either be done like in `emissionsapi/db.py` via environment variables or done after #11 and be configurable via the configuration file.

**Comment by frangiz** [comment]
Hey, I can fix this if you want. Will fix a PR for you.

**Comment by lkiesow** [comment]
Hi @frangiz, we are happy to get any contributions. If you want to tackle this, go ahead. Though, please be aware that we started this recently and things might still change quite rapidly. Which on the other hand also means: Feel free to make suggestions for changes if you think they make sense.

**Comment by lkiesow** [comment]
This is also somewhat related to #19

**Comment by lkiesow** [comment]
Since I'm working on the configuration right now anyway, I'm just fixing this along the way.

**Comment by frangiz** [comment]
@lkiesow , sounds good.
