### ISSUE TITLE
Get Timestamp from nc files

### ISSUE THREAD

**Issue by shaardie** [emissions-api/emissions-api#16]
All the data we get from the nc files have a timestamp. We should also load and store those.

- [x] load time stamps
- [x] convert to absolute times
- [ ] store in database

**Comment by frangiz** [comment]
How do I get a hold on one of the files? The download code is not yet implemented and I cannot find any documentation where they are.

**Comment by shaardie** [comment]
They can be downloaded by from the ESA, see here https://s5phub.copernicus.eu/dhus/#/home. Currently we are only interested in the carbon monoxide data and only in the L2 Data (the already processed one).

But you can also take a shortcut and simply use this file https://data.lkiesow.de/emissions-api/S5P_NRTI_L2__CO_____20190921T104303_20190921T104803_10045_01_010302_20190921T124803.nc :smile:

**Comment by shaardie** [comment]
@frangiz Also for more details about the data, we started a [documentation repository](https://github.com/emissions-api/documentation) with some useful links on how to work with the data.

**Comment by lkiesow** [comment]
Yesterday, I also implemented a temporary download which is already merged. Right now, it's also just downloading a single file from my server:

https://github.com/emissions-api/emissions-api/blob/ee48ee28bcfdab08649955b18e9a6221427f0cd8/emissionsapi/download.py#L16-L24

**Comment by frangiz** [comment]
Got the timestamps using netCDF4,  but not yet able to get them with the gdal library.

**Comment by lkiesow** [comment]
My guess would be that we want to use `//PRODUCT/delta_time`:

```sh
% gdalinfo data/S5P_NRTI_L2__CO_____20190921T122303_20190921T122803_10046_01_010302_20190921T130405.nc| grep -i //PRODUCT.\*time
SUBDATASET_42_NAME=HDF5:"data/S5P_NRTI_L2__CO_____20190921T122303_20190921T122803_10046_01_010302_20190921T130405.nc"://PRODUCT/delta_time
  SUBDATASET_42_DESC=[1x373] //PRODUCT/delta_time (32-bit integer)
```

More info:

```
% gdalinfo data/S5P_NRTI_L2__CO_____20190921T122303_20190921T122803_10046_01_010302_20190921T130405.nc| grep -i time
…
  PRODUCT_delta_time_long_name=offset of start time of measurement relative to time_reference                                                                                                                                                 
  PRODUCT_delta_time_units=milliseconds since 2019-09-21 00:00:00
…
  time_reference=2019-09-21T00:00:00Z
  time_reference_days_since_1950=25465 
  time_reference_julian_day=2458747.5 
  time_reference_seconds_since_1970=1569024000
```

gdalinfo is quite handy when it comes to working with this data. So is Panoply.
@shaardie, are these the timestamps you wanted to use?

**Comment by lkiesow** [comment]
Yep, looking at the [Sentinal-5p manual: Chapter 8.4 Time information](http://www.tropomi.eu/sites/default/files/files/Sentinel-5P-Level-2-Product-User-Manual-Formaldehyde_v1.01.01_20180716.pdf) it seems like that is what we want.

**Comment by frangiz** [comment]
For some reason I thought that you wanted the time_utc and that one was harder.

**Comment by lkiesow** [comment]
Re-opening this since I've extended the todo list.

**Comment by frangiz** [comment]
Found some metadata to use for recalculation:
time_coverage_duration -> PT312.472S
time_coverage_end -> 2019-09-21T12:28:10Z
time_coverage_resolution -> PT0.840S
time_coverage_start -> 2019-09-21T12:22:57Z
time_reference -> 2019-09-21T00:00:00Z
time_reference_days_since_1950 -> 25465
time_reference_julian_day -> 2458747.5
time_reference_seconds_since_1970 ->
