### ISSUE TITLE
ID Range Too Small

### ISSUE THREAD

**Issue by lkiesow** [emissions-api/emissions-api#171]
We are currently using a 4-byte serial (autoincrementing integer) [with a range of 1 to 2147483647](https://www.postgresql.org/docs/9.1/datatype-numeric.html). From the 10 months we imported, we already have approximately 950,000,000 values. Importing the full two years would likely exceed the index range. Hence we either need to drop the ID (#168) or use another data type like bigserial.

**Comment by shaardie** [comment]
I am in favor of dropping the ID. Maybe best together with dropping the ORM.
