### ISSUE TITLE
OpenAPI spec has unsupported type "date-time"

### ISSUE THREAD

**Issue by marcoarthur** [emissions-api/emissions-api#291]
Hello,

Trying to use the OApi specification I just got that the "date-time" is not a supported type
( https://github.com/jhthorsen/mojolicious-plugin-openapi/issues/192 ), as the developer of a OA implementation for Mojo
came to point to me: 

https://swagger.io/specification/#data-types

**Comment by lkiesow** [comment]
You are right, the

https://github.com/emissions-api/emissions-api/blob/d9de35b0223a7884ef427b782aa47be1804315f7/emissionsapi/openapi.yml#L282-L284

should probably be:

```yml
type: string
format: date-time
```

Can you create a pull request to fix that?

**Comment by marcoarthur** [comment]
Hi @lkiesow ,

Sure, I have made already the modification (https://github.com/marcoarthur/emissions-api/commit/ea9a7ba408a24875559de613b373841e3d7e2371), but, the perl Mojo OpenAPI implementation still not validating the Spec, so I am trying to understand the problem before make a PR:

<pre>
Invalid JSON specification file:///home/itaipu/src/emissions-api/emissionsapi/openapi.yml
- /components/parameters/product/$ref: /oneOf/0 Missing property.
- /components/parameters/product/required: /oneOf/1 Expected boolean - got string.
- /components/parameters/product/schema/enum: /oneOf/1/oneOf/0 Expected array - got object.
- /components/parameters/product/schema/$ref: /oneOf/1/oneOf/1 Missing property. at /home/itaipu/perl5/perlbrew/perls/perl-5.28.2/lib/site_perl/5.28.2/JSON/Validator.pm line 168.
	JSON::Validator::load_and_validate_schema(JSON::Validator::OpenAPI::Mojolicious=HASH(0x559aa16bd350), "file:///home/itaipu/src/emissions-api/emissionsapi/openapi.yml", HASH(0x559aa3690348)) called at /home/itaipu/perl5/perlbrew/perls/perl-5.28.2/lib/site_perl/5.28.2/JSON/Validator/OpenAPI/Mojolicious.pm line 40
	JSON::Validator::OpenAPI::Mojolicious::load_and_validate_schema(JSON::Validator::OpenAPI::Mojolicious=HASH(0x559aa16bd350), "file:///home/itaipu/src/emissions-api/emissionsapi/openapi.yml", HASH(0x559aa3690348)) called at /home/itaipu/perl5/perlbrew/perls/perl-5.28.2/lib/site_perl/5.28.2/Mojolicious/Plugin/OpenAPI.pm line 35
	Mojolicious::Plugin::OpenAPI::register(Mojolicious::Plugin::OpenAPI=HASH(0x559aa36903a8), Mojolicious::Lite=HASH(0x559aa19e4fd8), HASH(0x559aa16a2328)) called at /home/itaipu/perl5/perlbrew/perls/perl-5.28.2/lib/site_perl/5.28.2/Mojolicious/Plugins.pm line 45
	Mojolicious::Plugins::register_plugin(Mojolicious::Plugins=HASH(0x559aa16d3aa0), "OpenAPI", Mojolicious::Lite=HASH(0x559aa19e4fd8), HASH(0x559aa16a2328)) called at /home/itaipu/perl5/perlbrew/perls/perl-5.28.2/lib/site_perl/5.28.2/Mojolicious.pm line 178
	Mojolicious::plugin(Mojolicious::Lite=HASH(0x559aa19e4fd8), "OpenAPI", HASH(0x559aa16a2328)) called at /home/itaipu/perl5/perlbrew/perls/perl-5.28.2/lib/site_perl/5.28.2/Mojolicious/Lite.pm line 45
	main::plugin("OpenAPI", HASH(0x559aa16a2328)) called at emissions.pl line 4
</pre>
