### ISSUE TITLE
Dowloaded data ends with .zip instead of .nc

### ISSUE THREAD

**Issue by shaardie** [emissions-api/emissions-api#43]
This is a known issue in SentinelSat see https://github.com/sentinelsat/sentinelsat/issues/270

We should

* [ ] temporary fix that in our `download.py` to be able to preprocess those data further
* [ ] Fix that upstream. Funnily enough, this issue is tagged with hacktoberfest and good-first-issue. So catch it!

**Comment by benszau** [comment]
@lkiesow Did you allready work on this issue (on the upstream par)?

**Comment by lkiesow** [comment]
A fix is available at sentinelsat/sentinelsat#320
