### ISSUE TITLE
Request Data from PostgreSQL

### ISSUE THREAD

**Issue by lkiesow** [emissions-api/emissions-api#5]
Get data for specific requests.
We should be able to:

- [x] Request a geometry frame (rectangle)
- [ ] Request a date range (time interval)

**Comment by shaardie** [comment]
@lkiesow What do you mean by `data range`?

**Comment by shaardie** [comment]
There are now function to get the points from within a polygon and a rectangle in `db.py`.

**Comment by lkiesow** [comment]
I mean that you should be able to specify a time interval or something like that. Updated the description

**Comment by shaardie** [comment]
Request with rectangles are done. Request via timestamp are quite easy with SQLAlchemy. As soon as those timestamp are in the data, see #17, this should be pretty straight forward. So a attach the good-first-issue label.
