### ISSUE TITLE
Convert Data to GeoJSON

### ISSUE THREAD

**Issue by lkiesow** [emissions-api/emissions-api#6]

**Comment by shaardie** [comment]
@lkiesow Do you have something special in mind here?

* SQLAlchemy Query to Feature Collection?
* Object to Feature?
* Object List to Feature Collection? 

or something else?

**Comment by lkiesow** [comment]
I don't care about the internal structure, I just want GeoJSON as output ;-)

**Comment by shaardie** [comment]
Okay, then I would consider this as done, see https://github.com/emissions-api/emissions-api/blob/ee48ee28bcfdab08649955b18e9a6221427f0cd8/emissionsapi/web.py#L44-L56
