### ISSUE TITLE
Improve Logging

### ISSUE THREAD

**Issue by lkiesow** [emissions-api/emissions-api#67]
Right now Emissions API is barely logging any information. For example, it would be nice to get information about what stage of the pre-processing the tool is in when executing the `preprocess` module.

**Comment by dalisaydavid** [comment]
👋 I can help you out here!

**Comment by shaardie** [comment]
The Pull Request to this issue was closed, since the corresponding parts have moved to https://github.com/emissions-api/sentinel5algorithms. Also there is logging for the different steps of the preprocess right now. Closing...
