### ISSUE TITLE
Unify time parsing

### ISSUE THREAD

**Issue by shaardie** [emissions-api/emissions-api#68]
We are currently using the `iso8601` and the default python `datetime.datetime.fromisoformat` to parse time strings.

We probably should try to use the same library for the parsing of time string and maybe even pull [dateutil](https://pypi.org/project/python-dateutil/) as a dependency to our project.

**Comment by dalisaydavid** [comment]
👋 @shaardie I'm looking for Python repos that require hacktoberfest help. The only timestamp formatting library I see is `datetime`.

**Comment by shaardie** [comment]
Hej @dalisaydavid. Great that you like to help us. As mentioned above we are currently using both `datetime.datetime.fromisoformat` and the [iso8601](https://pypi.org/project/iso8601/) library.

Another great library which can parse nearly everything would be [dateutil](https://pypi.org/project/python-dateutil/).

I assign the issue to you.

**Comment by dalisaydavid** [comment]
Woops, yes. I realized that when I forked.

The `datetime` module should be good enough. And it sounds like you want 1 module to do all of these things related to timestamps. Let me work on that.

**Comment by dalisaydavid** [comment]
I saw `emissions-api` is [using Python 3.6](https://github.com/emissions-api/emissions-api/blob/6531a62cacc581236db689b0af5f37fecbe64152/.travis.yml#L8). But I see [`datetime.datetime.fromisoformat` is in Python 3.7](https://docs.python.org/3.7/library/datetime.html#datetime.date.fromisoformat). Which Python version should `emissions-api` be using?
