### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by lkiesow** [emissions-api/emissions-api#7]
- [x] Create endpoint `/api/v1/geo.json`
    - [x] Parameter `geoframe=[lo1,la1,lo2,la2]`
    - [ ] Parameter `begin=YYYY-MM-DD`
    - [ ] Parameter `end=YYYY-MM-DD`
- [x] Get data from PostgreSQL (#5)
- [x] Convert data to GeoJSON (#6 )

**Comment by frangiz** [comment]
Hey, I can fix this the begin and end parameters together with some validation and tests.

**Comment by shaardie** [comment]
Hej @frangiz. Great that you want to help with this project. As you can see we just started this.

Currently the data in the database do not contain any timestamps, so currently it will not be possible to filter the result after the date. So if you want to work on this, maybe you can take a look at #16 or #17 first.

**Comment by frangiz** [comment]
@shaardie , sure thing.
