### ISSUE TITLE
Depenceny Management

### ISSUE THREAD

**Issue by shaardie** [emissions-api/emissions-api#80]
We want to

* Freeze the version of dependencies without C-library backends
* Leave dependencies with accompanying C-libraries untouched or set them to a version range if required
* Integrate [Dependabot](https://dependabot.com/) to take care of dependency updates (meaning that the bot would automatically create pull requests for new library versions which we would still need to test)

like proposed in #75.

**Comment by lkiesow** [comment]
Just wondering, but isn't it a bit superfluous to create a new issue with basically the same content and close the other one just because it is labeled `question`? I would just have removed the `question` label :wink:

**Comment by lkiesow** [comment]
Dependabot is attached.
