### ISSUE TITLE
Consider extracting data processing libraries

### ISSUE THREAD

**Issue by lkiesow** [emissions-api/emissions-api#81]
Like we did with [sentinel5dl](https://github.com/emissions-api/sentinel5dl) for downloading data files, we might want to consider extracting the data processing algorithms in its own library which we then just call from the main project.

There are a number of advantages to this:

- a smaller codebase for each project making it easier to start work with it
- the library would be re-usable for other projects even if the API is not
- it might be easier to document and understand algorithms we included

**Comment by shaardie** [comment]
I like this idea very much and I think we should do it as soon as #64 is resolved.

**Comment by shaardie** [comment]
Or we wait for #73 :smile:

**Comment by EmbeddedHenni** [comment]
+1 for a clear code base in this project and more code reusability

**Comment by tibroc** [comment]
Ok, this was done over the weekend. The corresponding repository can be found [here](https://github.com/emissions-api/sentinel5algorithms).

**Comment by shaardie** [comment]
@tibroc I think we should not close this, until #91 is merged.
