### ISSUE TITLE
Estimate amount of data

### ISSUE THREAD

**Issue by lkiesow** [emissions-api/emissions-api#82]
Based on an import of a certain amount of data sets (e.g. 5GB of data) we should estimate how big our database will end up and if we can still handle something like that with the API in its current form.

**Comment by shaardie** [comment]
On our test setup we downloaded all carbon monoxide data sets from February 2019 which contains data from Germanyand ended up with

* 63 downloaded files
* 8GB downloaded data
* 11min download time

We processed this raw data files and ended up with

* 43592325 carbon monoxide entries in the database
* The PostgreSQL database directory was 7.5GB (This does not mean a lot)
* ca 16h of processing times

**Comment by lkiesow** [comment]
[PostgreSQL: How to show table sizes](https://makandracards.com/makandra/52141-postgresql-how-to-show-table-sizes)

**Comment by lkiesow** [comment]
Tests with four month of data. Caching is deactivated.

Reference requests to our demo server which has one month imported:
```
% repeat 6 /usr/bin/time -p curl -s -X GET "https://demo.emissions-api.org/api/v1/average.json?begin=2019-02-01&end=2019-03-01&cache=false" -o /dev/null 2>&1 | grep real
real 32.07
real 20.44
real 13.04
real 12.86
real 13.57
real 13.83
```

Local with four month of data:
```
% repeat 6 /usr/bin/time -p curl -s -X GET "http://127.0.0.1:5000/api/v1/average.json?begin=2019-02-01&end=2019-03-01&cache=false" -o /dev/null 2>&1 | grep real
real 319.75
real 141.58
real 253.01
real 241.94
real 146.90
real 140.84
```

Amount of data:
```
> select count(*) from carbonmonoxide;
   count   
-----------
 406759405
(1 row)

Time: 118727.018 ms (01:58.727)
```

Range of data:
```
> select min(timestamp), max(timestamp) from carbonmonoxide;
           min           |           max           
-------------------------+-------------------------
 2019-01-01 03:05:00.537 | 2019-05-01 02:30:00.476
(1 row)

Time: 119644.767 ms (01:59.645)
```

Size of database tables:
```
        relation        | total_size 
------------------------+------------
 public.carbonmonoxide  | 59 GB
```

Database storage on disk:
```
df -h /var/lib/pgsql/data/
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdc1       110G   62G   43G  60% /var/lib/pgsql/data
```

The estimated size for two years would be a database of around 360GB.

**Comment by shaardie** [comment]
We have estimated this more than once now. And also have read data for over a year to make assumptions on.
